### ISSUE TITLE
add support for kong upstream objects

### ISSUE THREAD

**Issue by eoly** [ontic/ansible-role-kong#2]
I'd like to be able to manage Kong upstream objects with Ansible.

https://docs.konghq.com/0.14.x/admin-api/#upstream-objects

**Comment by adamdyson** [comment]
Time permitted, I will try and add support for this tonight, or the day after.

**Comment by adamdyson** [comment]
I've managed to add support for the Upstream and Target API's in [v2.4.5](https://github.com/ontic/ansible-role-kong/releases/tag/v2.4.5). It wasn't as easy and clean as I would have liked due to those endpoints either using the old DAO, missing methods or not functioning as expected.

I'll leave this issue open for now, let me know how you get on.

**Comment by eoly** [comment]
Thanks, I'll get a chance to test this soon.

**Comment by eoly** [comment]
This works great for me. Thank you!
